Scriptname MantellaAdvancedAction_Follow extends Quest hidden

;This script is an example of an independent Mantella action
;Independent actions can be added without modifying Mantella code.
;The only dependencies are 'soft' dependencies
;An independent action requires only the following:
;  - A quest, defined within any .esp/.esl/esm
;  - A script, attached to that quest
;  - A JSON file, describing the action and its parameters, placed in Mantella's 'Actions' folder.
;

;Example variables that might be used by this action. 
;You can remove or add any variables you need, just make sure to initialize them properly in the InitVars function below.
Actor PlayerRef 
MantellaRepository  repository 
MantellaConstants  mConsts 
MantellaInterface  EventInterface 
MantellaConversation  conversation 

;Our event identifier, must match the one in the JSON
string ACTION_FOLLOW = "mantella_npc_follow" const

;To avoid using properties and creating hard dependencies on Mantella scripts, 
;we need to initialize all variables by getting the relevant forms directly from the game.
Function InitVars()
    PlayerRef = Game.GetPlayer()
    Form conversationForm = Game.GetFormFromFile(0x066FBB, "Mantella.esp") ; MantellaConversation
    Form questForm = Game.GetFormFromFile(0x000F99, "Mantella.esp") ; MantellaQuest

    if conversationForm == none || questForm == none
         Debug.TraceUser("MC", "Error initializing MantellaAdvancedAction_Follow: Could not find required Mantella forms")
         return
    EndIf

    conversation = conversationForm as MantellaConversation
    repository = questForm as MantellaRepository
    mConsts =conversationForm as MantellaConstants
    EventInterface = conversationForm as MantellaInterface
    Debug.TraceUser("MC", "Follow Variables initialized: conversation=" + conversation + ", repository=" + repository + ", mConsts=" + mConsts + ", EventInterface=" + EventInterface)
EndFunction

; OnInit is called when the quest is first added to the game, which can be at game start or when loading a save that never had this quest before.
event OnInit()
    Debug.OpenUserLog("MC")
    InitVars()

    ;define the event name we want to listen for, which is the prefix + our action identifier defined in the JSON file for this action
    string eventName = EventInterface.EVENT_ADVANCED_ACTIONS_PREFIX + ACTION_FOLLOW
    ;
    ;Or you can use one of the standard action identifiers defined in MantellaConstants
    ;string eventName = EventInterface.EVENT_ADVANCED_ACTIONS_PREFIX + mConsts.ACTION_NPC_FOLLOW
    
    Debug.TraceUser("MC", "Follow Registering for follow event: " + eventName)
    RegisterForExternalEvent(eventName, "OnNpcFollowAdvancedActionReceived")
EndEvent

; This function will get called whenever Mantella raises the event that the player performed in the conversation.
; Parameters:
;  - speakerID: the FormID of the actor that performed the action, passed as an int. You can convert it back to an Actor using Game.GetForm(speakerID) as Actor
;  - unused: a string parameter that is not used.
;  - argumentsHandle: an int handle that you can use to get a dictionary of arguments transmitted from Mantella. This is useful for actions that require more information, such as which NPC the action should be performed on. 
;    You can use MantellaPlugin.getString(argumentsHandle, key) or MantellaPlugin.getInt(argumentsHandle, key) to extract the relevant information using the keys defined in your JSON file for this action.

Function OnNpcFollowAdvancedActionReceived(int speakerID, string unused, int argumentsHandle)
    ;If you need the speaker of the action, you can get it using the speakerID parameter. 
    Actor speaker = None
    if speakerID != 0
        speaker = Game.GetForm(speakerID) as Actor
    EndIf

    ; If arguments handle is -1, then this event is a legacy action that does not support advanced parameters, so we handle it differently.
    ; Advanced actions are generated by the LLM's tool calling feature, if available.
    ; Legacy actions are triggered when the LLM generates a specific keyword, the 'key' defined in the JSON file, within its response that Mantella recognizes as an action.
    ; This capability is not guaranteed with all LLMs and is less reliable.

    if argumentsHandle == -1
        Debug.TraceUser("MC", "Received follow legacy action event")
        if speaker != none
            NpcFollow(speaker)
        EndIf
        return
    Else
        string[] sourceNames = MantellaPlugin.getStringArray(argumentsHandle, mConsts.ACTION_ARG_SOURCE)
        Debug.TraceUser("MC", "Received follow advanced action event for NPCs: " + sourceNames.Length)
        
        ; Resolve each name to an Actor reference
        int i = 0
        While i < sourceNames.Length
            Actor sourceActor = conversation.GetActorByName(sourceNames[i])
            if sourceActor != none
                NpcFollow(sourceActor)
            endIf
            i += 1
        EndWhile
    Endif
endFunction

Function NpcFollow(Actor speaker)
    if (speaker)
        Faction CompanionFaction = Game.GetForm(0x000023C01) as Faction
        ;Actor speaker = conversation.GetActorSpokenTo(playerRef)
        ;NPCs not yet available as companions have -1 faction rank
        if repository.allowNPCsStayInPlace && (!speaker.IsinFaction(CompanionFaction) || speaker.GetFactionRank(CompanionFaction) < 0)
            Debug.Notification(speaker.GetDisplayName() + " is following")
            speaker.SetPlayerTeammate(true)
            speaker.EvaluatePackage()
        EndIf
    endif
EndFunction